### ISSUE TITLE
Group By Does not work

### ISSUE THREAD

**Issue by wiichog** [Gmousse/dataframe-js#52]
Hi,
When I try to do a group by this error shows

TypeError: Cannot read property 'apply' of undefined
    at \node_modules\dataframe-js\lib\modules\sql\sqlEngine.js:224:30
    at sqlParser (\node_modules\dataframe-js\lib\modules\sql\sqlEngine.js:244:12)
    at Function.request (\node_modules\dataframe-js\lib\modules\sql\index.js:34:47)
    at app.js:263:39
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at next (\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at \node_modules\express\lib\router\index.js:281:22
    at Function.process_params (\node_modules\express\lib\router\index.js:335:12)

I'm sure I have data to do the group by and this is the query im tyring to run

select longitude,latitude,sum(amount),idfraudpoint from tmp0 where fraud=1 GROUP BY idfraudpoint

**Comment by Gmousse** [comment]
Hi @wiichog

In order to see if the bug is due to the sql module or the groupby itself, can you try to run your computation without the sql module (by using the Dataframe methods)?

Thanks

**Comment by Gmousse** [comment]
Closes after more than 1 month of inactivity
